# Generated by Django 3.0.8 on 2020-07-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_hub_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehub',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagehub',
            name='number_of_downloads',
            field=models.IntegerField(null=True, verbose_name='downloads'),
        ),
        migrations.AlterField(
            model_name='imagehub',
            name='number_of_views',
            field=models.IntegerField(null=True, verbose_name='view'),
        ),
    ]
