# Generated by Django 3.0.8 on 2020-07-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_hub_app', '0003_auto_20200727_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehub',
            name='number_of_views',
            field=models.IntegerField(blank=True, null=True, verbose_name='view'),
        ),
    ]
