# Generated by Django 3.0.8 on 2020-07-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_hub_app', '0004_auto_20200727_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehub',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
