# Generated by Django 3.0.8 on 2020-07-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_hub_app', '0008_auto_20200728_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehub',
            name='number_of_downloads',
            field=models.IntegerField(default=0, verbose_name='downloads'),
        ),
    ]
